In [4]:
import pandas as pd
import numpy as np

league_2017_ml = pd.read_csv('csv_data/_training.testing.ml.csv')

### apply one-hot encoding

In [5]:
data  = league_2017_ml.values
Abbrev = data[:, 0]
Seeding = data[:, 1]
Conference = data[:,2]
Division = data[:,3]
Label = data[:, 45 ]

In [6]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()

In [7]:
label_encoder.fit(Abbrev)
encoded_abbrev = label_encoder.transform(Abbrev)

In [8]:
label_encoder.fit(Seeding)
encoded_seeding = label_encoder.transform(Seeding)

In [9]:
label_encoder.fit(Conference)
encoded_conference = label_encoder.transform(Conference)

In [10]:
label_encoder.fit(Division)
encoded_division = label_encoder.transform(Division)

In [11]:
label_encoder.fit(Label)
encoded_label = label_encoder.transform(Label)

In [27]:
concatenate = {'Abbrev': encoded_abbrev,
               'Seeding': encoded_seeding,
               'Conference': encoded_conference,
               'Division': encoded_division, 
               'Label': encoded_label,
               }

encoding_df = pd.DataFrame(data = concatenate, )

In [32]:
encoding_df

     Abbrev  Conference  Division  Label  Seeding
0         0           1         3      1       11
1         1           1         3      0       10
2         2           0         0      0       10
3         3           0         0      0       10
4         4           0         2      0       10
5         5           0         2      0       10
6         6           1         3      0       10
7         7           1         1      1        6
8         8           1         1      0       10
9         9           1         1      1        4
10       10           0         0      1        3
11       11           1         3      0       10
12       12           0         0      1        1
13       13           1         3      1       12
14       14           1         1      1       14
15       15           0         0      0       10
16       16           0         2      0       10
17       17           1         1      1       14
18       18           0         2      1       14
19       19           0         2      1        9
20       20           0         0      0       10
21       21           0         2      1       14
22       22           0         2      1        8
23       23           1         3      1       13
24       24           1         1      1        5
25       25           0         0      1        2
26       26           0         0      0       10
27       27           1         3      0       10
28       28           1         1      0       10
29       29           0         2      1        7
..      ...         ...       ...    ...      ...
210       0           1         3      1       11
211       1           1         3      0       10
212       2           0         0      1        0
213       3           0         0      0       10
214       4           0         2      0       10
215       5           0         2      1        9
216       6           1         3      1       14
217       7           1         1      1        4
218       8           1         1      0       10
219       9           1         1      0       10
220      10           0         0      0       10
221      11           1         3      1       12
222      12           0         0      0       10
223      13           1         3      0       10
224      14           1         1      1        5
225      15           0         0      1        1
226      16           0         2      0       10
227      17           1         1      1       14
228      18           0         2      0       10
229      19           0         2      1       14
230      20           0         0      1        2
231      21           0         2      0       10
232      22           0         2      1        8
233      23           1         3      1       13
234      24           1         1      1        6
235      25           0         0      0       10
236      26           0         0      1       14
237      27           1         3      0       10
238      28           1         1      0       10
239      29           0         2      1        7

[240 rows x 5 columns]

In [35]:
# encoding_df.to_csv('csv_data/encoded_df.csv', index = False)

### Neural Network

In [37]:
encoded_ml = pd.read_csv('csv_data/encoded_df.csv')
encoded_ml.head()

,Label,Abbrev,Conference,Division,Seeding,Season End,Cumulative Games,Points,Corsi Close,Fenwick Close,...,M Agnst Up 1,B% Down 1,B For Down 1,B Agnst Down 1,B% Tied,B For Tied,B Agnst Tied,B% Up 1,B For Up 1,B Agnst Up 1
0,1,0,1,3,11,2016,82,103,53.68,54.06,...,154,59.13,149,103,52.45,385,349,48.63,195,206
1,0,1,1,3,10,2016,82,78,45.65,45.07,...,199,55.06,196,160,45.38,295,355,43.02,154,204
2,0,2,0,0,10,2016,82,93,49.87,50.06,...,176,53.98,156,133,51.31,392,372,41.82,161,224
3,0,3,0,0,10,2016,82,81,47.02,46.92,...,138,51.19,215,205,47.49,340,376,41.22,115,164
4,0,4,0,2,10,2016,82,86,51.55,50.73,...,159,60.19,195,129,54.29,424,357,47.80,163,178

In [38]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from keras.utils import to_categorical

Using TensorFlow backend.

In [39]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, random_state = 1, stratify = y)

NameError: name 'X' is not defined

In [ ]:
X_scaler = StandardScaler().fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)